collections:
  - name: community.general
  - name: ansible.posix
  - name: community.vmware
  - name: https://github.com/mikemorency/vmware.vmware.git
    type: git
    version: feature/make-dpm-options-match-ui